estimated_gas_cost_of_withdraw = "100000"
max_total_home_contract_balance = "10000000000000000000"
max_single_deposit_value = "1000000000000000000"

[home]
account = "0x43EC6d0942f7fAeF069F7F63D0384a27f529B062"
ipc = "/Users/CodeR/Dropbox/ChainSafe/Shyft/shyft_go-ethereum/shyftData/geth.ipc"
required_confirmations = 0

[home.contract]
bin = "contracts/EthereumBridge.bin"

[foreign]
account = "0x43EC6d0942f7fAeF069F7F63D0384a27f529B062"
ipc = "/Users/CodeR/Dropbox/ChainSafe/Shyft/shyft_go-ethereum/shyftData/geth.ipc"
required_confirmations = 0

[foreign.contract]
bin = "contracts/KovanBridge.bin"

[authorities]
accounts = [
	"0x43EC6d0942f7fAeF069F7F63D0384a27f529B062",
]
required_signatures = 1

[transactions]
home_deploy = { gas = 1000000 }
foreign_deploy = { gas = 3000000 }
deposit_relay = { gas = 150000 }
withdraw_relay = { gas = 100000 }
withdraw_confirm = { gas = 300000 }
